baseURL = "https://antvd.space"
title = "AntVD.Space"
languageCode = "en-us"
theme = "london"
logo = ""
sectionPagesMenu = "main"
## Content Blocks
[params]
    mainSections = ["projects", "articles"]
## Main Menu
[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "https://antvd.space"
[[menu.main]]
    name = "Articles"
    identifier = "articles"
    weight = 2
    url = "/articles"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 3
    url = "/projects"
[[menu.main]]
    name = "Curriculum"
    identifier = "curriculum"
    weight = 4
    url = "/curriculum"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 5
    url = "/about"
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 6
    url = "/contact"
