---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/about.yaml
  label: About me
- type: document
  path: data/front.yaml
  label: Main Front Content
- type: directory
  path: data/jobs
  label: Jobs
  create: documents
  match: "**/*"
  new_doc_ext: yml
  templates:
  - jobs
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - basic-article
  - photo-essay
upload_dir: AntvdUploads
public_path: https://res.cloudinary.com/dmw0znxgj/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
