---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data/jobs
  label: Job Board
  create: documents
  match: "**/*"
  new_doc_ext: yml
  templates:
  - jobs
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
upload_dir: AntvdUploads
public_path: https://res.cloudinary.com/dmw0znxgj/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
